### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#102]
Hi Dev,

I have installed `tidal-wave` latest binary by using this command `python -m pip install tidal-wave[all]` on windows 10 based PC. I tried to download this album **https://tidal.com/browse/album/323681**

Album totally has 21 tracks out of which 19 tracks got successfully downloaded. But when it program tries to download the `tracks no - 20 & 21`. A very long program crash error log comes in terminal.

So, I have uninstalled the `tidal-wave` & installed using below command `python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/trunk.zip`. But issue remain same.

Have attached error in text file for ready ref.

[Tidal_Error_Log.txt](https://github.com/ebb-earl-co/tidal-wave/files/14585662/Tidal_Error_Log.txt)

Thanks

**Comment by ebb-earl-co** [comment]
This is quite strange. It is some sort of decoding problem, but I’ve never seen error output anything like it!

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 I am puzzled by this album. When I try to retrieve tracks with MQA quality using the `develop` branch, I get the following error for the album:
```bash
HTTPError: 404 Client Error: Not Found for url: https://api.tidal.com/v1/323681?countryCode=US&locale=en_US&deviceType=TV
```
I.e., the API cannot even find the album. However, when I switch to the [`httpx`](https://github.com/ebb-earl-co/tidal-wave/tree/httpx) branch, I can retrieve all the tracks in MQA or Low quality with no issue...

As to the error in your attached .txt file, that seems like an intermittent connection issue. Can you install the `httpx` branch and attempt to retrieve the album again? I.e.,
```powershell
PS > python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip
PS > python.exe -m tidal_wave https://tidal.com/browse/album/323681 --audio-format mqa --loglevel debug
```

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 I am puzzled by this album. When I try to retrieve tracks with MQA quality using the `develop` branch, I get the following error for the album:
> 
> ```shell
> HTTPError: 404 Client Error: Not Found for url: https://api.tidal.com/v1/323681?countryCode=US&locale=en_US&deviceType=TV
> ```
> 
> I.e., the API cannot even find the album. However, when I switch to the [`httpx`](https://github.com/ebb-earl-co/tidal-wave/tree/httpx) branch, I can retrieve all the tracks in MQA or Low quality with no issue...
> 
> As to the error in your attached .txt file, that seems like an intermittent connection issue. Can you install the `httpx` branch and attempt to retrieve the album again? I.e.,
> 
> ```powershell
> PS > python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip
> PS > python.exe -m tidal_wave https://tidal.com/browse/album/323681 --audio-format mqa --loglevel debug
> ```

I tried with 1st command & it gave below error.

Command used :-

`python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip`

Error Log :-

`Collecting https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip
 ERROR: HTTP error 404 while getting https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip
 ERROR: Could not install requirement https://github.com/ebb-earl-co/tidal-wave/archive/httpx.zip because of HTTP error 404 
 Client Error: Not Found for url: https://codeload.github.com/ebb-earl-co/tidal-wave/zip/httpx for URL https://github.com/ebb- 
 earl-co/tidal-wave/archive/httpx.zip`

**Comment by rajeshsahoo12** [comment]
`TRUNK BRANCH RESULTS`


I have uninstalled tidal-wave & installed using the command `python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/trunk.zip`. And installation was successful.

[tidal-wave (trunk) branch log.txt](https://github.com/ebb-earl-co/tidal-wave/files/14594161/tidal-wave.trunk.branch.log.txt)


And used this command to download track no 20 `tidal-wave https://tidal.com/browse/track/323701 --audio-format hires`. And output was only this in terminal.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/0d6686b7-d686-4aad-ab12-c57f000f7838)


Everytime I have opened new terminal to install & uninstall program for each branch along with downloading track command.

**Comment by rajeshsahoo12** [comment]
**MAKE IT FASTER BRANCH RESULTS**

I have uninstalled tidal-wave & installed using the command `python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/make-it-faster.zip`. And installation was successful.

[tidal-wave (make-it-faster) branch log.txt](https://github.com/ebb-earl-co/tidal-wave/files/14594188/tidal-wave.make-it-faster.branch.log.txt)


And used this command to download track no 20 `tidal-wave https://tidal.com/browse/track/323701 --audio-format hires`. And output was only this in terminal.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/781aefb3-d265-4351-bb27-a1cd0c0c0129)


Everytime I have opened new terminal to install & uninstall program for each branch along with downloading track command.

**Comment by rajeshsahoo12** [comment]
`DEVELOP BRANCH RESULTS`

I have uninstalled tidal-wave & installed using the command `python.exe -m pip install https://github.com/ebb-earl-co/tidal-wave/archive/develop.zip`. And installation was successful.

[tidal-wave (develop) branch log.txt](https://github.com/ebb-earl-co/tidal-wave/files/14594219/tidal-wave.develop.branch.log.txt)


And used this command to download track no 20 `tidal-wave https://tidal.com/browse/track/323701 --audio-format hires`. And output was only this in terminal.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/09fc4fb6-b13a-41f8-9704-58f60b185abc)


Everytime I have opened new terminal to install & uninstall program for each branch along with downloading track command.

**Comment by rajeshsahoo12** [comment]
I have tested now for track no - 20 is getting downloaded with audio-format flag with `low, high, lossless, mqa`. 

When flag `hires` is used & if program finds the track is available in `MQA format` inside default downloading path then program says `Even though HiRes audio format was requested, this track is only available in MQA format. TIDAL regards this as 'HiRes' even though it is probably only lossless; i.e. 16-bit 44.1 kHz quality. Downloading of track will continue, but it will be marked as MQA ([Q])` along with this message `Track C:\Users\Rajesh Sahoo\Music\Hombres G\Los Singles 1985-2005 [323681] [1993]\20 - Qué soy yo para ti (Radio Edit) [Q].flac already exists and therefore will not be overwritten` 


When flag `hires` is used & if program does not find the track in `MQA format` inside default downloading path then program says that long error in text file.

**Comment by ebb-earl-co** [comment]
> I have tested now for track no - 20 is getting downloaded with audio-format flag with `low, high, lossless, mqa`.
> 
> When flag `hires` is used & if program finds the track is available in `MQA format` inside default downloading path then program says `Even though HiRes audio format was requested, this track is only available in MQA format. TIDAL regards this as 'HiRes' even though it is probably only lossless; i.e. 16-bit 44.1 kHz quality. Downloading of track will continue, but it will be marked as MQA ([Q])` along with this message `Track C:\Users\Rajesh Sahoo\Music\Hombres G\Los Singles 1985-2005 [323681] [1993]\20 - Qué soy yo para ti (Radio Edit) [Q].flac already exists and therefore will not be overwritten`
> 
> When flag `hires` is used & if program does not find the track in `MQA format` inside default downloading path then program says that long error in text file.

At the very least, now we know that the track you're looking for is *not* available in HiRes format, just MQA. So, if you've got it downloaded already in MQA format, what's the follow-on problem?

**Comment by rajeshsahoo12** [comment]
> > I have tested now for track no - 20 is getting downloaded with audio-format flag with `low, high, lossless, mqa`.
> > When flag `hires` is used & if program finds the track is available in `MQA format` inside default downloading path then program says `Even though HiRes audio format was requested, this track is only available in MQA format. TIDAL regards this as 'HiRes' even though it is probably only lossless; i.e. 16-bit 44.1 kHz quality. Downloading of track will continue, but it will be marked as MQA ([Q])` along with this message `Track C:\Users\Rajesh Sahoo\Music\Hombres G\Los Singles 1985-2005 [323681] [1993]\20 - Qué soy yo para ti (Radio Edit) [Q].flac already exists and therefore will not be overwritten`
> > When flag `hires` is used & if program does not find the track in `MQA format` inside default downloading path then program says that long error in text file.
> 
> At the very least, now we know that the track you're looking for is _not_ available in HiRes format, just MQA. So, if you've got it downloaded already in MQA format, what's the follow-on problem?

I do not have further problem. Was just posted my test results form my end in all possible cases.

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 okay good. It could be a transient issue with your network or the TIDAL API... In any case, I'll hold off merging in the `make-it-faster` changes for now as they seem to be disruptive.

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 okay good. It could be a transient issue with your network or the TIDAL API... In any case, I'll hold off merging in the `make-it-faster` changes for now as they seem to be disruptive.

Okay sure.
