### ISSUE TITLE
getting 2ch stereo output m4a instead of multichannel for 360RA

### ISSUE THREAD

**Issue by tcafranz** [ebb-earl-co/tidal-wave#110]
am I doing something wrong? How do I get the 8 or 12 channels?

**Comment by tcafranz** [comment]
this is from MediaInfo:

General 
CompleteName : C:\Users\*****\Music\Justin Timberlake\Everything I Thought It Was [350639046] [2024]\14 - What Lovers Do [360].m4a 
Format/String : iso8 
CodecID/String : iso8 (mp41/dash/cmfc) 
FileSize/String : 2.78 MiB 
Duration/String : 3 min 42 s 
OverallBitRate_Mode/String : Constant 
OverallBitRate/String : 105 kb/s 
Cover : Yes 

Audio 
ID/String : 1 
Format/String : AAC LC SBR 
Format/Info : Advanced Audio Codec Low Complexity with Spectral Band Replication 
Format_Commercial_IfAny : HE-AAC 
Format_Settings : NBC 
CodecID : enca-40 / mp4a-5 
Duration/String : 3 min 42 s 
BitRate_Mode/String : Constant 
BitRate/String : 96.0 kb/s 
Channel(s)/String : 2 channels 
ChannelLayout : L R 
SamplingRate/String : 44.1 kHz 
FrameRate/String : 21.533 FPS (2048 SPF) 
Compression_Mode/String : Lossy 
StreamSize/String : 2.55 MiB (92%) 
Encryption : Encrypted 
ConformanceErrors : 1 
 Crosscheck : Yes 
  CMAF : Yes 
   channelConfiguration : CMAF does not permit USAC UsacConfig channelConfigurationIndex 0, permitted values are 1 and 2

**Comment by ebb-earl-co** [comment]
@tcafranz thank you for having raised an issue! You're the first person to have raised an issue to do with the Sony 360 RA format, so I haven't looked at it in a while. What *should* happen is that the track(s) is/are downloaded as a .mka file...

From the `mediainfo` output, that track is a regular old AAC stereo audio, not Sony 360 RA. What was the command that you used for this track? If you want to try again, it should be
```bash
$ tidal-wave https://listen.tidal.com/album/350639046 --audio-format 360 --loglevel debug
```
If you execute that, could you get the logs and add it as a file to your response here on GitHub?

**Comment by tcafranz** [comment]
@ebb-earl-co [PowerShell 7 (x86)_tidal-wave 360RA debug.txt](https://github.com/ebb-earl-co/tidal-wave/files/14662670/PowerShell.7.x86._tidal-wave.360RA.debug.txt)

yea I don't even know where to start with all this but here you go. Appreciate the help. I've managed to get Dolby Atmos 6 channels just fine but never had any success with 360RA until yesterday when I actually got it to download SOMETHING. 

The command I used to get that file was

`$ tidal-wave --audio-format 360 https://tidal.com/browse/track/350639062`

**Comment by ebb-earl-co** [comment]
I’m not a Powershell expert, but near the end of the logs you added, it seems to be complaining that there is no `ffmpeg` installed on your system. Have you got `ffmpeg`?

Separately, in order to retrieve Sony 360 audio files, you need an access token from an [Android device](https://tidal.com/supported-devices?filter=sony-360) (TIDAL’s specification, not mine). It looks as if you used the access token from a Windows machine, which works great, but only for HiRes.

**Comment by tcafranz** [comment]
😭 I only have apple or windows to get access token from.... ughhhh... yes I have ffmpeg I don't know why it's saying I don't. I wouldn't suppose you'd be kind enough to grab that album for me (well for my wife).  🫤

**Comment by ebb-earl-co** [comment]
@tcafranz if you have no Android devices, it's possible to use something like [BlueStacks](https://www.bluestacks.com/) to get an Android virtual machine on your Windows host, but I haven't done that...

**Comment by tcafranz** [comment]
@ebb-earl-co thanks ill check it out.
