### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#113]
Hi Dev,

I use this script to download ALAC, ATMOS, PLAYLIST from apple music `https://github.com/zhaarey/apple-music-alac-atmos-downloader`

But the script does not download selective track from album. Let assume if we have a album which has `10 tracks` & I want to get only `track no - 04`. Here is the url from which I want to download `track no - 04` `https://music.apple.com/in/album/bajenge/1736449575?i=1736450031`

So, I hope u can help on this if possible.

Thanks

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 you will have to create an issue in the GitHub page for that project, not here. I can’t help you with someone else’s project that is new to me
