### ISSUE TITLE
pyapp is still not built in 2024.3.5.2

### ISSUE THREAD

**Issue by eevan78** [ebb-earl-co/tidal-wave#120]
pyapp binary artifact is still not building, even after hotfix...

**Comment by ebb-earl-co** [comment]
@eevan78, thank you for having raised this. Sadly, PyPi was under attack by some malicious actors, so my changes were not able to be sent to PyPi; thus, the `tidal-wave` artifacts could not be built. This should be resolved with 2024.3.6!

**Comment by ebb-earl-co** [comment]
@eevan78 the Windows release artifact is available in [the newest release](https://github.com/ebb-earl-co/tidal-wave/releases/tag/2024.3.6). Direct link to the file: [here](https://github.com/ebb-earl-co/tidal-wave/releases/download/2024.3.6/tidal-wave_py311.pyapp.exe)
