### ISSUE TITLE
Dolby Atmos Does Not Downloads

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#132]
Hi Dev,

I am using `tidal-wave` latest release & tried downloading this track in `DOLBY ATMOS` format. But unfortunately, it does not gets downloaded. Here is the url of track `https://tidal.com/browse/track/295322685?u`

Command I have used to download is `tidal-wave https://tidal.com/browse/track/295322685?u --audio-format atmos`

Error log :-

`2024-04-02:04:02:12,099 INFO     [models.py:668] TIDAL track ID parsed from input: 295322685
2024-04-02:04:02:12,729 INFO     [requesting.py:95] Requesting from TIDAL API: tracks/295322685
2024-04-02:04:02:13,773 INFO     [requesting.py:95] Requesting from TIDAL API: albums/295322684
2024-04-02:04:02:14,794 INFO     [requesting.py:95] Requesting from TIDAL API: tracks/295322685/credits
2024-04-02:04:02:15,817 INFO     [requesting.py:95] Requesting from TIDAL API: tracks/295322685/playbackinfopostpaywall
2024-04-02:04:02:16,177 WARNING  [requesting.py:107] 401 Client Error: Unauthorized for TIDAL API endpoint tracks/295322685/playbackinfopostpaywall`

To make sure this track is in `DOLBY ATMOS`, I tried same track with `HIRES` audio format & here below have attached the terminal output. It means track is in ``DOLBY ATMOS` format.

`2024-04-02:04:01:59,933 INFO     [models.py:668] TIDAL track ID parsed from input: 295322685
2024-04-02:04:01:59,934 INFO     [login.py:151] Loading TIDAL access token from 'C:\Users\Rajesh Sahoo\AppData\Local\tidal-wave\android-tidal.token'
2024-04-02:04:02:00,812 INFO     [login.py:175] Access token is valid: saving to 'C:\Users\Rajesh Sahoo\AppData\Local\tidal-wave\android-tidal.token'
2024-04-02:04:02:00,814 INFO     [requesting.py:95] Requesting from TIDAL API: tracks/295322685
2024-04-02:04:02:01,688 WARNING  [track.py:681] Track 295322685 is only available in Dolby Atmos format. Downloading of track will not continue.`

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 can you tell me
1. What OS you're using to execute this (it looks like Windows)
2. Whether other Dolby Atmos tracks are able to be downloaded successfully

Then, can you retry to get this track and add `--loglevel debug` at the end?

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 can you tell me
> 
> 1. What OS you're using to execute this (it looks like Windows)
> 2. Whether other Dolby Atmos tracks are able to be downloaded successfully
> 
> Then, can you retry to get this track and add `--loglevel debug` at the end?

Yeah I am using windows 10. No I have tried many `DOLBY ATMOS` tracks but the results are same.

**Comment by rajeshsahoo12** [comment]
> --loglevel debug

I have ran the below command with `--loglevel debug` flag. And the results are shared.

https://justpaste.it/f5zq9 = `This is for binary release tidal-wave-2024.3.6`

https://justpaste.it/e6qgu = `This is for binary release tidal-wave-2024.3.5.2`

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 I have downloaded the track you originally mentioned with no problem, and in the logs you’re getting a 401: Unauthorized response… 

Is it just Dolby Atmos for which you are getting these responses? My first thought is that your account lapsed and you haven’t paid for TIDAL HiFi. That might cause this 🤷

**Comment by Rajeshsahoo12** [comment]
> @Rajeshsahoo12 I have downloaded the track you originally mentioned with no problem, and in the logs you’re getting a 401: Unauthorized response…
> 
> Is it just Dolby Atmos for which you are getting these responses? My first thought is that your account lapsed and you haven’t paid for TIDAL HiFi. That might cause this 🤷

**Comment by rajeshsahoo12** [comment]
> I have downloaded the track you originally mentioned with no problem

Ohhhh okay. But I am able to download hi-res files with same account access token. I am having HIFI PLUS FAMILY account.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/60ae9ea4-4e9d-4f87-af72-19fd4c746a5f)

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 I have downloaded the track you originally mentioned with no problem, and in the logs you’re getting a 401: Unauthorized response…
> 
> Is it just Dolby Atmos for which you are getting these responses? My first thought is that your account lapsed and you haven’t paid for TIDAL HiFi. That might cause this 🤷

Hi-Res files are not having any issue with same account access token. Here is the mediainfo of the same tracks which was downloading in terminal.

https://mediaarea.net/MediaBin/yKZaN3RC

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/58f1b302-a7e4-4ce8-8d3a-b56ea52a4f6a)

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 I have downloaded the track you originally mentioned with no problem, and in the logs you’re getting a 401: Unauthorized response…
> 
> Is it just Dolby Atmos for which you are getting these responses? My first thought is that your account lapsed and you haven’t paid for TIDAL HiFi. That might cause this 🤷

I have tried using this repo script `https://github.com/Dniel97/orpheusdl-tidal` for downloading `DOLBY ATMOS` track. I have used the same account for the login in program. And it is able to download the `DOLBY ATMOS` track.


Command used to download `python orpheus.py https://tidal.com/browse/track/295322685` . And here I have attached the mediainfo for the downloaded file. `https://mediaarea.net/MediaBin/bZqcINHP`


![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/58f319c1-4d63-4545-a27b-4c6d0f4b0805)

**Comment by ebb-earl-co** [comment]
How strange… I was about to retrieve this track (and the rest of the album) without issue, and it seems that you were able to retrieve the track from the TIDAL API with another project…

I really do not know to what to attribute the error you are experiencing, especially because it’s a 401 unauthorized response.

**Comment by rajeshsahoo12** [comment]
> https://github.com/Dniel97/orpheusdl-tidal

Ohhh. Okay. Yeah it is strange behavior. I thought may be this is issue with my `ISP`, so I have tried with same account access token & `tidal-wave` latest binary release on vps too. But the error is same. So, definately it is not issue with machine. 

And one more thing is for login process it is not asking for any access token. In 1st start of the module it generates with device linking link & awaits for the login process to be finished. It is same as the fire-tv access token login happens on ur project./

And that's it. And it generates `config. json` which can also be modified as per ur needs.

**Comment by rajeshsahoo12** [comment]
> How strange… I was about to retrieve this track (and the rest of the album) without issue, and it seems that you were able to retrieve the track from the TIDAL API with another project…
> 
> I really do not know to what to attribute the error you are experiencing, especially because it’s a 401 unauthorized response.

As I remember well & it was mentioned here in readme that to extract `HiRes FLAC, Dolby Atmos, and Sony 360 Reality Audio tracks` we need to have access token extracted from android device / windows device.


![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/d06f2bb0-e408-42b7-bd68-776e600e27fa)


So, I use android device access token to rip `HIRES & DOLBY ATMOS`.



But now I have deleted all of my existing token inside config folder. And when I tried to rip `DOLBY ATMOS` track with fresh access token from android device inside config folder.

It says below msg in terminal now it is asking for fire-tv access token. Which is I think there has been some changes with code.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/f3cf384e-af65-44d7-9620-e65746aee5e9)



And voilla after successfull login to my account with provided device link url. Program got the fire-tv access token & it successfully downloaded the track which were trying. Here is the success msg.


![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/814b22d6-a97b-43e1-a83e-11995fc11644)



Thanks dev for being patient about it.

**Comment by ebb-earl-co** [comment]
> > How strange… I was about to retrieve this track (and the rest of the album) without issue, and it seems that you were able to retrieve the track from the TIDAL API with another project…
> > I really do not know to what to attribute the error you are experiencing, especially because it’s a 401 unauthorized response.
> 
> As I remember well & it was mentioned here in readme that to extract `HiRes FLAC, Dolby Atmos, and Sony 360 Reality Audio tracks` we need to have access token extracted fro android device / windows device. So, I use android device access token to rip `HIRES & DOLBY ATMOS`
> 
> But now I have deleted all of my existing token inside config folder. And when I tried to rip `DOLBY ATMOS` track with fresh access token from android device. It says below msg in terminal now it is asking for fire-tv access token. Which is I think there has been some changes with code.
> 
> ![image](https://private-user-images.githubusercontent.com/54216637/320103666-f3cf384e-af65-44d7-9620-e65746aee5e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDIzMDUsIm5iZiI6MTcxMjM0MjAwNSwicGF0aCI6Ii81NDIxNjYzNy8zMjAxMDM2NjYtZjNjZjM4NGUtYWY2NS00NGQ3LTk2MjAtZTY1NzQ2YWVlNWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE4MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYTRhMjk3NTBhMjBlNmRhMDdkOWJjNGQ0ZGUzNTM1Y2Y5Y2Y1OTA1M2ZjMmU2NGFhZDFlMzhmZTEzMzIwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.si4htmU3syce-UHU2D9tJCbXDV5Kaoglf_VVvVw03QE)
> 
> ![image](https://private-user-images.githubusercontent.com/54216637/320101246-d06f2bb0-e408-42b7-bd68-776e600e27fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDIzMDUsIm5iZiI6MTcxMjM0MjAwNSwicGF0aCI6Ii81NDIxNjYzNy8zMjAxMDEyNDYtZDA2ZjJiYjAtZTQwOC00MmI3LWJkNjgtNzc2ZTYwMGUyN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE4MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGI5MWJkYjRiNDRiNGNhZjA5ZTcwZTg5NDdhY2FkOTczOGFiMjNiOGRlYmMxZTE3NzEyYWMwN2Q2MzBmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mfCCznlK23nf8b4tzooWdEAz1QocmgMmjFEIpr9LMKo)

If you’re talking about the code for `tidal-wave`, then it has always been the case that Dolby Atmos tracks are retrieved with the spoofed Fire TV parameters.

The TIDAL website does list Android as a Dolby Atmos-capable client, but there must be some other code inside the TIDAL for Android app that I don’t have a way to replicate. Thus, Atmos is retrieved with the spoofed Fire TV credentials.

**Comment by ebb-earl-co** [comment]
> > https://github.com/Dniel97/orpheusdl-tidal
> 
> Ohhh. Okay. Yeah it is strange behavior. I thought may be this is issue with my `ISP`, so I have tried with same account access token & `tidal-wave` latest binary release on vps too. But the error is same. So, definately it is not issue with machine.
> 
> And one more thing is for login process it is not asking for any access token. In 1st start of the module it generates with device linking link & awaits for the login process to be finished. It is same as the fire-tv access token login happens on ur project./
> 
> And that's it. And it generates `config. json` which can also be modified as per ur needs.

Is this project capable of retrieving HiRes or Sony 360 tracks?

**Comment by rajeshsahoo12** [comment]
> > > How strange… I was about to retrieve this track (and the rest of the album) without issue, and it seems that you were able to retrieve the track from the TIDAL API with another project…
> > > I really do not know to what to attribute the error you are experiencing, especially because it’s a 401 unauthorized response.
> > 
> > 
> > As I remember well & it was mentioned here in readme that to extract `HiRes FLAC, Dolby Atmos, and Sony 360 Reality Audio tracks` we need to have access token extracted fro android device / windows device. So, I use android device access token to rip `HIRES & DOLBY ATMOS`
> > But now I have deleted all of my existing token inside config folder. And when I tried to rip `DOLBY ATMOS` track with fresh access token from android device. It says below msg in terminal now it is asking for fire-tv access token. Which is I think there has been some changes with code.
> > ![image](https://private-user-images.githubusercontent.com/54216637/320103666-f3cf384e-af65-44d7-9620-e65746aee5e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDIzMDUsIm5iZiI6MTcxMjM0MjAwNSwicGF0aCI6Ii81NDIxNjYzNy8zMjAxMDM2NjYtZjNjZjM4NGUtYWY2NS00NGQ3LTk2MjAtZTY1NzQ2YWVlNWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE4MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYTRhMjk3NTBhMjBlNmRhMDdkOWJjNGQ0ZGUzNTM1Y2Y5Y2Y1OTA1M2ZjMmU2NGFhZDFlMzhmZTEzMzIwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.si4htmU3syce-UHU2D9tJCbXDV5Kaoglf_VVvVw03QE)
> > ![image](https://private-user-images.githubusercontent.com/54216637/320101246-d06f2bb0-e408-42b7-bd68-776e600e27fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDIzMDUsIm5iZiI6MTcxMjM0MjAwNSwicGF0aCI6Ii81NDIxNjYzNy8zMjAxMDEyNDYtZDA2ZjJiYjAtZTQwOC00MmI3LWJkNjgtNzc2ZTYwMGUyN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE4MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGI5MWJkYjRiNDRiNGNhZjA5ZTcwZTg5NDdhY2FkOTczOGFiMjNiOGRlYmMxZTE3NzEyYWMwN2Q2MzBmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mfCCznlK23nf8b4tzooWdEAz1QocmgMmjFEIpr9LMKo)
> 
> If you’re talking about the code for `tidal-wave`, then it has always been the case that Dolby Atmos tracks are retrieved with the spoofed Fire TV parameters.
> 
> The TIDAL website does list Android as a Dolby Atmos-capable client, but there must be some other code inside the TIDAL for Android app that I don’t have a way to replicate. Thus, Atmos is retrieved with the spoofed Fire TV credentials.

Ohhhhh okay. I got it.

**Comment by rajeshsahoo12** [comment]
> > > https://github.com/Dniel97/orpheusdl-tidal
> > 
> > 
> > Ohhh. Okay. Yeah it is strange behavior. I thought may be this is issue with my `ISP`, so I have tried with same account access token & `tidal-wave` latest binary release on vps too. But the error is same. So, definately it is not issue with machine.
> > And one more thing is for login process it is not asking for any access token. In 1st start of the module it generates with device linking link & awaits for the login process to be finished. It is same as the fire-tv access token login happens on ur project./
> > And that's it. And it generates `config. json` which can also be modified as per ur needs.
> 
> Is this project capable of retrieving HiRes or Sony 360 tracks?

Yes it does `HIRES` , `DOLBY ATMOS` , `MQA` & `360 RA`

For `HIRES` I have downloaded the same tracks using both projects `https://tidal.com/browse/track/294592079`. Here below is the mediainfo for the both files :-

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/a50b69cc-5b22-4c6e-88ff-dc3ba29f89ad)


https://mediaarea.net/MediaBin/NWRtTinl = Using `tidal-wave`

https://mediaarea.net/MediaBin/Xs07WeN2 = Using `orpheusdl-tidal`





For `DOLBY ATMOS` I have downloaded the same tracks using both projects `https://tidal.com/browse/track/295322685`. Here below is the mediainfo for the both files :-


![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/f5cc824a-c4a4-4896-9800-3bb12af8e4b7)


https://mediaarea.net/MediaBin/CcAOnmyu = Using `tidal-wave`

https://mediaarea.net/MediaBin/TMFSXGJ7 = Using `orpheusdl-tidal`



For `360RA` I have downloaded the same tracks using both projects `https://tidal.com/browse/track/354739558`. Here below is the mediainfo for the both files :-

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/dcbabfcf-fb7b-4acf-8a93-014132c6617b)


https://mediaarea.net/MediaBin/lXhTbjMp = Using `tidal-wave`

https://mediaarea.net/MediaBin/bXqMDAJG = Using `orpheusdl-tidal`


Thanks

**Comment by ebb-earl-co** [comment]
Excellent. Well, if you continue to hit problems with this project, you have a backup!

**Comment by rajeshsahoo12** [comment]
> Excellent. Well, if you continue to hit problems with this project, you have a backup!

I can think why I was getting error. May be fire-tv access token old in the tidal-wave config folder. Yesterday I have deleted it & reconnected the device with tidal.  So, fresh access token got generated for fire-tv login mode. And it worked.

Thanks
