### ISSUE TITLE
Gui on termux 

### ISSUE THREAD

**Issue by Notorious2Beat** [ebb-earl-co/tidal-wave#154]
Is there a way to get a ui on termux like tidal-dl yet?

**Comment by ebb-earl-co** [comment]
@Notorious2Beat sadly, I have no Android development or GUI development skills so I have no timeline for something like this…

**Comment by Notorious2Beat** [comment]
> @Notorious2Beat sadly, I have no Android development or GUI development skills so I have no timeline for something like this…

Ok thanks for your work
