### ISSUE TITLE
Playlist downloading feature only gets first 100 items

### ISSUE THREAD

**Issue by metronidazole** [ebb-earl-co/tidal-wave#155]
Not sure if this is an limitation of the API or this app, but if you try to download a playlist it will only grab the first 100 items.

**Comment by ebb-earl-co** [comment]
@metronidazole it’s not a limitation of the API, it’s that I h have not found an elegant way to retrieve more than 100 yet. Call it a bug, because I’m working on it

**Comment by ebb-earl-co** [comment]
See #115
