### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by Notorious2Beat** [ebb-earl-co/tidal-wave#27]
Where do I enter it?

**Comment by ebb-earl-co** [comment]
@Notorious2Beat when you want to retrieve Dolby Atmos or HiRes or Sony 360 Reality Audio, you'll pass one of those options on the command line. When you press enter, the program will prompt you for whether you want to use an access token from Android or Windows:
![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/dfd3c690-b219-44d3-b683-6a2ebb18287b)

As soon as you select one of those, the next prompt should be this:
![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/30c640ed-8482-4bbf-be81-ad2fca0e7710)

paste *just* the token, which probaby starts with eyJ

**Comment by Notorious2Beat** [comment]
> @Notorious2Beat when you want to retrieve Dolby Atmos or HiRes or Sony 360 Reality Audio, you'll pass one of those options on the command line. When you press enter, the program will prompt you for whether you want to use an access token from Android or Windows:
> ![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/dfd3c690-b219-44d3-b683-6a2ebb18287b)
> 
> As soon as you select one of those, the next prompt should be this:
> ![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/30c640ed-8482-4bbf-be81-ad2fca0e7710)
> 
> paste *just* the token, which probaby starts with eyJ

Sorry I meant for  termux app

**Comment by ebb-earl-co** [comment]
> > @Notorious2Beat when you want to retrieve Dolby Atmos or HiRes or Sony 360 Reality Audio, you'll pass one of those options on the command line. When you press enter, the program will prompt you for whether you want to use an access token from Android or Windows:
> > ![image](https://private-user-images.githubusercontent.com/11299014/293818934-dfd3c690-b219-44d3-b683-6a2ebb18287b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDgwNTksIm5iZiI6MTcwNDI0Nzc1OSwicGF0aCI6Ii8xMTI5OTAxNC8yOTM4MTg5MzQtZGZkM2M2OTAtYjIxOS00NGQzLWI2ODMtNmEyZWJiMTgyODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMmY2ZTAyODI5MzQ3ZjA4ZmQ0Y2RhNWExOTYxNjlmYmUxMDA5YzgxNzJmZThiYzBhNmU4ZWViYjhiZTNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVjMHe27_4Jnb4YhudFJbtlho0_ZZtSYeJq8v1SQklw)
> > As soon as you select one of those, the next prompt should be this:
> > ![image](https://private-user-images.githubusercontent.com/11299014/293819142-30c640ed-8482-4bbf-be81-ad2fca0e7710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDgwNTksIm5iZiI6MTcwNDI0Nzc1OSwicGF0aCI6Ii8xMTI5OTAxNC8yOTM4MTkxNDItMzBjNjQwZWQtODQ4Mi00YmJmLWJlODEtYWQyZmNhMGU3NzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjdiNWViYmQ0Y2U3NWY5ODAxMGY2ZDFlMjhkZDViMGY3YTc2MzY4MmEwYjBmZjZmOTJjMmE1ODMwYjIxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iAHtAo8FDGGqXU8MKUvdJjYDD_bAWzNf2eobnIPESAY)
> > paste _just_ the token, which probaby starts with eyJ
> 
> Sorry I meant for termux app

@Notorious2Beat sorry, I don't know much about Termux. If it's able to run Python code, then you follow the instructions in the README like any other platform. But I don't have a good way to test this, and I don't claim it as a supported platform yet, so please be the guinea pig and report back!

**Comment by Notorious2Beat** [comment]
> > > @Notorious2Beat when you want to retrieve Dolby Atmos or HiRes or Sony 360 Reality Audio, you'll pass one of those options on the command line. When you press enter, the program will prompt you for whether you want to use an access token from Android or Windows:
> > > ![image](https://private-user-images.githubusercontent.com/11299014/293818934-dfd3c690-b219-44d3-b683-6a2ebb18287b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDgwNTksIm5iZiI6MTcwNDI0Nzc1OSwicGF0aCI6Ii8xMTI5OTAxNC8yOTM4MTg5MzQtZGZkM2M2OTAtYjIxOS00NGQzLWI2ODMtNmEyZWJiMTgyODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMmY2ZTAyODI5MzQ3ZjA4ZmQ0Y2RhNWExOTYxNjlmYmUxMDA5YzgxNzJmZThiYzBhNmU4ZWViYjhiZTNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVjMHe27_4Jnb4YhudFJbtlho0_ZZtSYeJq8v1SQklw)
> > > As soon as you select one of those, the next prompt should be this:
> > > ![image](https://private-user-images.githubusercontent.com/11299014/293819142-30c640ed-8482-4bbf-be81-ad2fca0e7710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDgwNTksIm5iZiI6MTcwNDI0Nzc1OSwicGF0aCI6Ii8xMTI5OTAxNC8yOTM4MTkxNDItMzBjNjQwZWQtODQ4Mi00YmJmLWJlODEtYWQyZmNhMGU3NzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjdiNWViYmQ0Y2U3NWY5ODAxMGY2ZDFlMjhkZDViMGY3YTc2MzY4MmEwYjBmZjZmOTJjMmE1ODMwYjIxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iAHtAo8FDGGqXU8MKUvdJjYDD_bAWzNf2eobnIPESAY)
> > > paste _just_ the token, which probaby starts with eyJ
> > 
> > Sorry I meant for termux app
> 
> @Notorious2Beat sorry, I don't know much about Termux. If it's able to run Python code, then you follow the instructions in the README like any other platform. But I don't have a good way to test this, and I don't claim it as a supported platform yet, so please be the guinea pig and report back!

I can download cd quality but just can't enter my access token from tidal

**Comment by ebb-earl-co** [comment]
@Notorious2Beat I've just got my hands on someone's Pixel 4a (5G) running Graphene OS (so, not Android, but I believe it's still analogous) and I was able to add access token and download tracks:
1. `pkg install python`
2. `pkg install ffmpeg`
3. `python3 -m pip install tidal-wave`
4. `tidal-wave https://tidal.com/browse/track/226092704 --audio-format hires`

Then, I got the access token from the TIDAL logs on the very same phone, and pasted it into the Termux terminal and... it all downloaded just fine :man_shrugging:

**Comment by Notorious2Beat** [comment]
> @Notorious2Beat I've just got my hands on someone's Pixel 4a (5G) running Graphene OS (so, not Android, but I believe it's still analogous) and I was able to add access token and download tracks:
> 1. `pkg install python`
> 2. `pkg install ffmpeg`
> 3. `python3 -m pip install tidal-wave`
> 4. `tidal-wave https://tidal.com/browse/track/226092704 --audio-format hires`
> 
> Then, I got the access token from the TIDAL logs on the very same phone, and pasted it into the Termux terminal and... it all downloaded just fine :man_shrugging:  

Yes this works thx u very much for your work
