### ISSUE TITLE
Not Able To Update On Ubuntu

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#34]
Hi,

As latest update is **2024.1.4**. But when give **pip install tidal-wave==2024.1.4** command on terminal. It gives below mentioned error.

pip install tidal-wave==2024.1.4

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement tidal-wave==2024.1.4 (from versions: 2023.12.0, 2023.12.2, 2023.12.3, 2023.12.4, 2023.12.5, 2023.12.6, 2023.12.7, 2023.12.8, 2023.12.9, 2023.12.10, 2023.12.11, 2023.12.12, 2023.12.13, 2024.1.1, 2024.1.2, 2024.1.3)

ERROR: No matching distribution found for tidal-wave==2024.1.4

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 try again

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 not to step on your desired workflow, but the `_py311.pyapp` binaries in the releases are quite nice for Ubuntu as they're self-contained and don't require Python3 or pip or dependence management at all.

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 try again

Yeah now it is done

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 not to step on your desired workflow, but the `_py311.pyapp` binaries in the releases are quite nice for Ubuntu as they're self-contained and don't require Python3 or pip or dependence management at all.

Ohhhh okay. So, when I want to update to latest release, then what is the command for it..?

**Comment by ebb-earl-co** [comment]
> > @Rajeshsahoo12 not to step on your desired workflow, but the `_py311.pyapp` binaries in the releases are quite nice for Ubuntu as they're self-contained and don't require Python3 or pip or dependence management at all.
> 
> Ohhhh okay. So, when I want to update to latest release, then what is the command for it..?

Again, this is totally optional, but you just navigate to the latest release page on GitHub for this project, https://github.com/ebb-earl-co/tidal-wave/releases/, and you download the .pyapp file: at the time of writing, it's `tidal-wave_2024.1.4_py311.pyapp`. Then, if you're on Ubuntu, you move the file to wherever you want and make it exectuable, then you can run *it* from your shell instead of invoking Python:
```bash
$ chmod +x ~/Downloads/tidal-wave_2024.1.4_py311.pyapp
$ mv ~/Downloads/tidal-wave_2024.1.4_py311.pyapp ~/Music/tidal-wave_py311.pyapp  # or wherever/whatever you want to name it
$ ~/Music/tidal-wave_py311.app --help
```
