### ISSUE TITLE
Settings help

### ISSUE THREAD

**Issue by Baldy18657** [ebb-earl-co/tidal-wave#72]
Hello, I got everything installed but cannot change the default music quality or directory. What is the command I need for this to change it to hires please

**Comment by ebb-earl-co** [comment]
Hi there, thanks for having made an issue. In order to use some other directory as the parent directory for downloads, you pass it as the second argument: e.g.
```bash
$ tidal-wave https://listen.tidal.com/album/123456789 ~/Desktop/music/TIDAL/ --loglevel debug
```

**Comment by Baldy18657** [comment]
Okay, thank you. So there is no way to change the default setting you have to override the download location evertime

**Comment by ebb-earl-co** [comment]
> Okay, thank you. So there is no way to change the default setting you have to override the download location evertime

No, not at the moment. You could create a Bash function or similar, but I’m trying to resist implementing more toggles than is necessary. KISS and all that
