### ISSUE TITLE
Not Able To Install Program

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#93]
Hi Dev,

I am trying to install tidal-wave program on windows 10 based PC using this command `python -m pip install tidal-wave`. But facing below error.

`
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/`

`ERROR: Could not find a version that satisfies the requirement tidal-wave (from versions: none)
ERROR: No matching distribution found for tidal-wave
`

**Comment by AVAEO** [comment]
> Hi Dev,
> 
> I am trying to install tidal-wave program on windows 10 based PC using this command `python -m pip install tidal-wave`. But facing below error.
> 
> ` WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/tidal-wave/`
> 
> `ERROR: Could not find a version that satisfies the requirement tidal-wave (from versions: none) ERROR: No matching distribution found for tidal-wave `

Hey! Does this happen with every pip package or just Tidal-Wave? Sometimes this can be caused by Python itself being a bit funky. Sometimes a reinstall of Python helps. If every package returns this error, a quick Google on StackOverflow gives this command: `curl https://bootstrap.pypa.io/get-pip.py | python`. 

N.B. I'm not the dev, just really like this project.

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 the error output that you've included is an HTTP error, letting you know that your `pip.exe`, however you installed it, is not able to find the resource over the Internet; i.e. it's saying that there is no such thing as `tidal-wave` at PyPi's repository. This is false, as I have just now installed it on my system (not Windows, but the point is that `tidal-wave` *IS* available from PyPi)
![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/69f0bd2e-cb20-43fc-9cd3-9c09f1177faf)

If you check out [this StackOverflow question](https://stackoverflow.com/questions/73021674/i-tried-to-install-packages-using-pip-but-i-got-this-error/73021722), you'll see that your error is an Internet connection error on your Windows system, nothing to do with `tidal-wave`.

**Comment by rajeshsahoo12** [comment]
> @Rajeshsahoo12 the error output that you've included is an HTTP error, letting you know that your `pip.exe`, however you installed it, is not able to find the resource over the Internet; i.e. it's saying that there is no such thing as `tidal-wave` at PyPi's repository. This is false, as I have just now installed it on my system (not Windows, but the point is that `tidal-wave` _IS_ available from PyPi) ![image](https://private-user-images.githubusercontent.com/11299014/311337982-69f0bd2e-cb20-43fc-9cd3-9c09f1177faf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjQ3NDUsIm5iZiI6MTcwOTkyNDQ0NSwicGF0aCI6Ii8xMTI5OTAxNC8zMTEzMzc5ODItNjlmMGJkMmUtY2IyMC00M2ZjLTljZDMtOWMwOWYxMTc3ZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE5MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MGI5NjdkZmRkYzk3ODEyZjQzZjAzNjhjN2JiMzI5MmQ3YWQ1NTdkODA5MjYyMTNkMGM0NjNkZTZkYTI0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.heRB6uWWK--jjMPOAvz6dgUhojv1T9rANJTc7H7dEf8)
> 
> If you check out [this StackOverflow question](https://stackoverflow.com/questions/73021674/i-tried-to-install-packages-using-pip-but-i-got-this-error/73021722), you'll see that your error is an Internet connection error on your Windows system, nothing to do with `tidal-wave`.

Ohhhh okay. I have tried re-installation of python entirely the same version 3.10.0

But sadly no success.

**Comment by ebb-earl-co** [comment]
Do you have a proxy active? For example, the Fiddler program acting as a man-in-the-middle proxy? Can you run a pretty "default" command and include the output?
```powershell
python.exe -m pip install pip --upgrade --verbose
```

**Comment by rajeshsahoo12** [comment]
> ```powershell
> python.exe -m pip install pip --upgrade --verbose
> ```

I ran this command `python.exe -m pip install pip --upgrade --verbose`



`python.exe -m pip install pip --upgrade --verbose`


`Using pip 24.0 from C:\Users\Rajesh Sahoo\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
Requirement already satisfied: pip in c:\users\rajesh sahoo\appdata\local\programs\python\python310\lib\site-packages (24.0)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/`

**Comment by rajeshsahoo12** [comment]
> Do you have a proxy active? For example, the Fiddler program acting as a man-in-the-middle proxy? Can you run a pretty "default" command and include the output?
> 
> ```powershell
> python.exe -m pip install pip --upgrade --verbose
> ```

I have fiddler installed but it is not running ryt now.

**Comment by rajeshsahoo12** [comment]
> Do you have a proxy active? For example, the Fiddler program acting as a man-in-the-middle proxy? Can you run a pretty "default" command and include the output?
> 
> ```powershell
> python.exe -m pip install pip --upgrade --verbose
> ```

How do I check whether I am running behind proxy..? I am just using one wrap dns 1.1.1.1 , 1.0.0.1 for IPv4 & 2606:4700:4700::1111 , 2606:4700:4700::1001 for IPv6

**Comment by rajeshsahoo12** [comment]
> > Do you have a proxy active? For example, the Fiddler program acting as a man-in-the-middle proxy? Can you run a pretty "default" command and include the output?
> > ```powershell
> > python.exe -m pip install pip --upgrade --verbose
> > ```
> 
> How do I check whether I am running behind proxy..? I am just using one wrap dns 1.1.1.1 , 1.0.0.1 for IPv4 & 2606:4700:4700::1111 , 2606:4700:4700::1001 for IPv6

I tried installing pandas now. It is installing successfully.

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/aaf538fe-cc26-4a4d-8263-d5d66a642341)

**Comment by rajeshsahoo12** [comment]
> > > Do you have a proxy active? For example, the Fiddler program acting as a man-in-the-middle proxy? Can you run a pretty "default" command and include the output?
> > > ```powershell
> > > python.exe -m pip install pip --upgrade --verbose
> > > ```
> > 
> > 
> > How do I check whether I am running behind proxy..? I am just using one wrap dns 1.1.1.1 , 1.0.0.1 for IPv4 & 2606:4700:4700::1111 , 2606:4700:4700::1001 for IPv6
> 
> I tried installing pandas now. It is installing successfully.
> 
> ![image](https://private-user-images.githubusercontent.com/54216637/311348521-aaf538fe-cc26-4a4d-8263-d5d66a642341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjcxOTMsIm5iZiI6MTcwOTkyNjg5MywicGF0aCI6Ii81NDIxNjYzNy8zMTEzNDg1MjEtYWFmNTM4ZmUtY2MyNi00YTRkLTgyNjMtZDVkNjZhNjQyMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE5NDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNTliY2JlNjQxZTBiNzk5ZjM1NTE4NjU1MmI0OGQwYzU5NzQ2NmNkMTgyNmUyYWJmNjUzNDBiYjIzODU4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUtHsCdiiXQe-QeUUkopfa1lbMVXUcu38HLoMK_TJv8)

Thanks @ebb-earl-co @AVAEO. Now it got installed. What I have done is undo the usage of cloudfare wrap dns, flushdns. Re-assure that python is added to PATH by verifying under ENVIRONMENT VARIABLES


![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/43ef8021-f578-43ae-acdc-c83a80407b94)
